const products1 = [
    {
        id: 1,
        image: "product5.jpg",
        name: "Vaseline Healthy Bright SPF Lotion",
        price: 292.5,
        mrp: 585,
        discount: "50% off",
        return_period:7,
    },
    {
        id: 2,
        image: "product6.jpg",
        name: "Garnier Bright Complete Face Wash",
        price: 174.5,
        mrp: 349,
        discount: "50% off",
        return_period:7,
    },
    {
        id: 3,
        image: "product7.jpg",
        name: "Parachute Advanced Gold Coconut Oil",
        price: 178.5,
        mrp: 357,
        discount: "50% off",
        return_period:7,
    },
    {
        id: 4,
        image: "product9.jpg",
        name: "Holland & Barrett Fat Metaboliser",
        price: 399.5,
        mrp: 800,
        discount: "50% off",
        return_period:7,
    },
    {
        id: 5,
        image: "product8.jpg",
        name: "Lacto Calamine SPF 50 Sunscreen",
        price: 174.5,
        mrp: 349,
        discount: "50% off",
        return_period:7,
    },
    {
        id: 6,
        image: "product10.jpg",
        name: "Johnson's Baby Skincare Wipes",
        price: 140,
        mrp: 280,
        discount: "50% off",
        return_period:7,
    },
    {
        id: 7,
        image: "product1.jpg",
        name: "Loreal Total Repair Shampoo",
        price: 200,
        mrp: 400,
        discount: "50% off",
        return_period:7,
    },
    {
        id: 8,
        image: "product2.jpg",
        name: "Nivea Men Fresh Deo",
        price: 180,
        mrp: 360,
        discount: "50% off",
        return_period:7,
    },
    {
        id: 9,
        image: "product3.jpg",
        name: "Fair And Handsome Creame",
        price: 120,
        mrp: 240,
        discount: "50% off",
        return_period:7,
    },
    {
        id: 10,
        image: "product4.jpg",
        name: "Ponds Super Light Gel",
        price: 110,
        mrp: 220,
        discount: "50% off",
        return_period:7,
    },
];

const products2 = [
    {
        image: "ad-img1.jpg",
    },
    {
        image: "ad-img2.jpg",
    },
    {
        image: "ad-img3.jpg",
    },
    {
        image: "ad-img4.jpg",
    },
    {
        image: "ad-img5.jpg",
    },
    {
        image: "ad-img6.jpg",
    },
    {
        image: "ad-img7.jpg",
    },
    {
        image: "ad-img8.jpg",
    },
    {
        image: "ad-img9.jpg",
    },
    {
        image: "ad-img10.jpg",
    },
];

const products3 = [
    {
        id: 11,
        image: "product21.jpg",
        name: "Essentail Handwash",
        price: 150,
        mrp: 300,
        discount: "50% off",
        return_period:7,
    },
    {
        id: 12,
        image: "product22.jpg",
        name: "Activated Charcoal Soaps",
        price: 100,
        mrp: 200,
        discount: "50% off",
        return_period:7,
    },
    {
        id: 13,
        image: "product23.jpg",
        name: "Lemon Face Wipes",
        price: 150,
        mrp: 300,
        discount: "50% off",
        return_period:7,
    },
    {
        id: 14,
        image: "product24.jpg",
        name: "Aloe Vera Skin Care Gel",
        price: 200,
        mrp: 400,
        discount: "20% off",
        return_period:7,
    },
    {
        id: 15,
        image: "product25.jpg",
        name: "Neem Tulsi FaceWash",
        price: 174.5,
        mrp: 349,
        discount: "50% off",
        return_period:7,
    },
    {
        id: 16,
        image: "product26.jpg",
        name: "Glycerin Bathing Soap (Pack of 6)",
        price: 600,
        mrp: 1200,
        discount: "50% off",
        return_period:7,
    },
    {
        id: 17,
        image: "product27.jpg",
        name: "Shikakai Shampoo",
        price: 200,
        mrp: 400,
        discount: "50% off",
        return_period:7,
    },
    {
        id: 18,
        image: "product28.jpg",
        name: "Essential Handwash",
        price: 140,
        mrp: 280,
        discount: "50% off",
        return_period:7,
    },
    {
        id: 19,
        image: "product29.jpg",
        name: "Life ORS",
        price: 120,
        mrp: 240,
        discount: "50% off",
        return_period:7,
    },
    {
        id: 20,
        image: "product30.jpg",
        name: "Moisturiser",
        price: 150,
        mrp: 300,
        discount: "50% off",
        return_period:7,
    },
];